### PR TITLE
Add `AsyncBenchmarkThreadHelper`

### LINKED ISSUE #1: Add async support to BenchmarkThreadHelper
@Stabzs asked about supporting async actions in the thread helper over at https://github.com/dotnet/BenchmarkDotNet/issues/147.

I think we can achieve this by accepting `Func<ValueTask>` actions, and adding a new `ValueTask ExecuteAndWaitAsync()` method. The `BenchmarkThreadHelper` can implement `IValueTaskSource` to prevent any extra allocations.

<s>I'm also thinking about including a `SynchronizationContext` so async continuations can be posted back to the helper thread (instead of going to the `ThreadPool` which is not allocation-free). Maybe that can be optional so the user can decide if they want that or not.</s> [Edit] This would add too much overhead.

### PR DESCRIPTION
**Pull request by timcassell**
Resolves #1

@Stabzs Please take a look.

### CODE REVIEW

**Comment by Stabzs** [comment]
This looks great! I'll do some testing with it to see how it compares to manually managing task arrays.

**Comment by timcassell** [comment]
@Stabzs What were your results? Did you find anything wrong with this implementation?

**Comment by Stabzs** [comment]
I've run a number of tests and while the memory is still a bit inconsistent, it doesn't seem to necessarily be any more inconsistent than setting backing arrays that are "fired" via manual reset events. As a result, this implementation is more flexible and easier to set up. I think it'll do the trick! It isn't perfect, but none of the approaches I've tried are and this was much more pleasant to use. Thanks for putting in the effort here!

**Comment by timcassell** [comment]
@Stabzs Could you share some of your test code? I'm curious why you're getting inconsistent memory measurements. Also, what runtime are you testing on? There are known memory measurement issues prior to .Net 7.

**Comment by Stabzs** [comment]
@timcassell  I apologize, I somehow missed this comment.

After digging in, it looks like mixing IterationSetup causes BDN to only do 1 op, resulting in non-uniform allocation distributions. I assume this is related to https://github.com/dotnet/BenchmarkDotNet/issues/1351.

After removing any iteration setup, I get perfectly consistent results for allocations, which is incredibly exciting. Thank you so much for the effort on this...it is a fantastic tool. I hope to see it added to BDN in the future :).

One aside, do you have a recommendation for adding `ValueTask<T>` methods to the helper? Currently I'm doing something like the following:

```
for (int i = 0; i < 5; i++)
{
    var id = i.ToString();
    _asyncBenchmarkThreadHelper.Add(() =>
    {
        var valueTask = ValueTaskDoWorkAsync(id);
        if (valueTask.IsCompletedSuccessfully)
        {
            valueTask.GetAwaiter().GetResult();
            return default;
        }

        return new ValueTask(valueTask.AsTask());
    });
}
```

If this seems reasonable, awesome. If I'm abusing the intended api, I'd love to know.

**Comment by timcassell** [comment]
Great, glad you got it figured out. 

I would just do it like this (but your method might save an allocation):

```cs
_asyncBenchmarkThreadHelper.Add(async () => await ValueTaskDoWorkAsync(id)) 
```

Also, you could make an extension to do that conversion if you want. 

Sadly, there's no way to convert a `ValueTask<T>` to `ValueTask` without any overhead. See https://github.com/dotnet/runtime/issues/67212

**Comment by Stabzs** [comment]
Easy enough :). It would depend on the method and in some cases, the method would save an allocation and the goal of the benchmark would be to reproduce that.

**Pull request merged**
